##
## Makefile for  in /u/all/vangys_c/public/mario/Graphic
## 
## Made by thomas dewitte
## Login   <dewitt_t@epitech.net>
## 
## Started on  Thu Jun  7 14:23:56 2012 thomas dewitte
## Last update Thu Jun  7 15:20:37 2012 thomas dewitte
##

NAME=	super_mario_tech

CC=	gcc `sdl-config --cflags --libs` -lSDL_image main_type.c

all:
	$(CC) -o $(NAME)